params:
  epochs: 1
  batch_size: 32
  validation_datasize: 5000
  loss_funciton: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  num_classes: 10
  patience: 5
  restore_best_weights: True


logs:
  logs_dir: log_dir
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_logs
